# apiVersion: datadoghq.com/v2alpha1
# kind: DatadogAgent
# metadata:
#   name: datadog
# spec:
#   global:
#     registry: docker.io/datadog
#     site: datadoghq.com
#     credentials:
#       apiSecret:
#         secretName: datadog-secret
#         keyName: api-key
#   features:
#     logCollection:
#       enabled: true
#       containerCollectAll: true
#     cws:
#       enabled: true
#     usm:
#       enabled: true
#     npm:
#       enabled: true
